news/blog/2022: MGR TTL Cache blog post
ceph/ceph.io pull request #332
Opened 2022-01-31 17:29 UTC by pereman2

Signed-off-by: Pere Diaz Bou <pdiazbou@redhat.com>

2022-02-01 07:59 UTC, alfonsomthd commented on src/en/news/blog/2022/mgr-ttlcache/index.md
> +coupled (to the daemon) structure of python modules that we know as: dashboard, prometheus, pg_autoscaler, orchestrators and many more.
```suggestion
Problems have been arising a while ago related to the scalability of the mgr daemon and the underlying tightly
coupled (to the daemon) structure of python modules like dashboard, prometheus, pg_autoscaler, orchestrators and many more.
```

2022-02-01 08:02 UTC, alfonsomthd commented on src/en/news/blog/2022/mgr-ttlcache/index.md
> +structures like OSDMap will increase proportionally in size and thus, increasing the latency of modules when they try to reach for
```suggestion
structures like OSDMap will increase proportionally in size and thus, increasing the latency of modules when they retrieve
```

2022-02-01 08:04 UTC, alfonsomthd commented on src/en/news/blog/2022/mgr-ttlcache/index.md
> +That will set a 10 seconds _time to live_ to each object cached.
```suggestion
That will set a 10 seconds _time to live_ to each cached object.
```

2022-02-01 08:05 UTC, alfonsomthd commented on src/en/news/blog/2022/mgr-ttlcache/index.md
> +the cache enabled and using a simple serialization tool like json is.
```suggestion
the cache enabled and using a simple serialization tool like json.
```

2022-02-01 08:07 UTC, alfonsomthd commented on src/en/news/blog/2022/mgr-ttlcache/index.md
> +that alleviates some of the workload, but there is more work to be done addresing scalability, debugabilitty, subinterpeters...
```suggestion
that alleviates some of the workload, but there is more work to be done addressing scalability, debuggabilitty, subinterpreters...
```
Also you can end with: `Stay Tuned!` :smile:

2022-02-01 09:29 UTC, alfonsomthd approved these changes

2022-02-02 19:03 UTC, Thingee requested changes
Thanks, @pereman2. I appreciate the submission. I have some grammar and spelling corrections, but otherwise, this LGTM! :+1:

2022-02-03 06:46 UTC, pereman2 commented
@Thingee Thank you, all checked.

2022-02-08 00:14 UTC, merged