Set base href on 404 page
ceph/ceph.io pull request #357
Opened 2022-02-25 15:04 UTC by djgalloway

Signed-off-by: David Galloway <dgallowa@redhat.com>

2022-02-25 15:05 UTC, djgalloway commented
This is live right now and working

2022-02-25 18:19 UTC, Thingee approved these changes
tested lgtm

2022-02-26 00:53 UTC, dmick requested changes

2022-02-26 01:47 UTC, djgalloway commented on src/_includes/layouts/_base.njk
> +    {% if 'Not found' in title %}<base href="https://ceph.io">{% endif %}
Maybe not?  But my thinking was "what is the likelihood of another blog post having 'Not found' in the title?"

2022-02-26 20:04 UTC, dmick approved these changes

2022-03-09 13:47 UTC, merged