en/news/blog/2022/three-large-scale-clusters: add blog post about gibba and the two scalelab clusters
ceph/ceph.io pull request #414
Opened 2022-07-18 07:03 UTC by ljflores

An installment in the "Quincy @ Scale" series.

Signed-off-by: Laura Flores <lflores@redhat.com>

2022-07-18 07:44 UTC, ljflores commented
Blog post rendered here: https://wip-three-scalable-clusters.ceph.io/en/news/blog/2022/three-large-scale-clusters/

2022-07-18 07:48 UTC, ljflores commented on src/en/news/blog/2022/three-large-scale-clusters/index.md
> +anonymization issue in the performance channel See the [Tracker Index](#gibba%3A-testing-telemetry) for details..
Note to self: Accidentally put two periods here-- fix. Will leave for now since there will probably be additional edits.

2022-07-19 21:00 UTC, vumrao requested changes

2022-07-19 21:00 UTC, vumrao commented on src/en/news/blog/2022/three-large-scale-clusters/index.md
> +   - Quincy is outperforming Pacific by 80% in 1-hr hybrid workload on new clusters.
Or I think we can go with what we have as we already mention the version number and already we have a tracker open to track this issue. @neha-ojha @ljflores WDYT?

2022-07-19 22:27 UTC, ljflores commented on src/en/news/blog/2022/three-large-scale-clusters/index.md
> +   - Quincy is outperforming Pacific by 80% in 1-hr hybrid workload on new clusters.
@vumrao perhaps the section just needs to be updated with our recent findings. We can remove the part about the performance boost being a sure thing and replace it with our current investigation on bluestore_zero_block_detection.

2022-07-20 21:33 UTC, ljflores commented on src/en/news/blog/2022/three-large-scale-clusters/index.md
> +Two sets of object sizes are typically employed in DFG testing. The generic sized workload uses:
@vumrao GitHub makes it a little hard to differentiate which line needs the change. Is it 133 that should say "RGW S3" instead of "DFG"?

2022-07-20 21:48 UTC, vumrao commented on src/en/news/blog/2022/three-large-scale-clusters/index.md
> +Two sets of object sizes are typically employed in DFG testing. The generic sized workload uses:
Thanks, @ljflores, you got it.

2022-07-22 19:31 UTC, ljflores commented
Folliwing a conversation with @vumrao, we will be replacing the 17.2.0 hybrid-new graph, which showed an 80% performance boost for Quincy, with a new graph for 17.2.1.

2022-07-22 23:03 UTC, Thingee approved these changes

2022-07-22 23:04 UTC, Thingee commented
Is this ready?

2022-07-23 03:19 UTC, Thingee commented
Apologies. I approved the wrong pull request.

2022-07-24 23:12 UTC, ljflores commented
> Apologies. I approved the wrong pull request.

@Thingee No worries, I will re-request your review once this blog post is finalized.

2022-08-02 23:05 UTC, ljflores commented
@vumrao @Thingee the date is set for tomorrow

2022-08-02 23:08 UTC, vumrao approved these changes
LGTM!

2022-08-04 15:13 UTC, ljflores commented
Force-pushed to update the date.

2022-08-04 15:47 UTC, ljflores commented
Spoke with @vumrao; we'll go ahead and merge this since everything looks fine.

2022-08-04 15:47 UTC, merged