community/events/ceph-days-nyc: Update one talk and add lightning talk
ceph/ceph.io pull request #489
Opened 2023-01-26 23:53 UTC by Thingee

Speaker cancellation.

Signed-off-by: Mike Perez <thingee@gmail.com>

2023-01-26 23:58 UTC, Thingee commented
Whoops, I need to fix Anthony's speaker photo.

2023-01-27 00:11 UTC, anthonyeleven requested changes
Someone's name became inserted in the text last year, and it's still here, please remove.

2023-01-27 00:11 UTC, anthonyeleven commented on src/en/community/events/2023/ceph-days-nyc/index.md
> +Ceph enables flexible and scalable object storage of unstructured data for a wide variety of workloads. RGW (RADOS GateWay) deployments experience a wide variety of object sizes and must balance work
s/Matt Vandermeulen//

2023-01-27 00:28 UTC, Thingee commented on src/en/community/events/2023/ceph-days-nyc/index.md
> +Ceph enables flexible and scalable object storage of unstructured data for a wide variety of workloads. RGW (RADOS GateWay) deployments experience a wide variety of object sizes and must balance work
Thanks, Anthony.

2023-01-27 00:29 UTC, Thingee commented
Dan's photo has been added.

2023-01-27 09:05 UTC, Thingee commented
If this is OK, please merge. There will be announcements going out this morning.

2023-01-27 13:54 UTC, anthonyeleven approved these changes

2023-01-27 13:54 UTC, merged