17.2.8 Release notes
ceph/ceph.io pull request #742
Opened 2024-11-11 22:18 UTC by yuriw

2024-11-12 22:29 UTC, zdover23 requested changes
@yuriw: I've made some suggestions for the addition of articles to sentences. 

If you tell me that it's okay to push to this branch, I'll take care of these alterations myself. I just wanted to make sure that you had agreed to it before I acted.

2024-11-12 22:29 UTC, zdover23 commented on src/en/news/blog/2024/v17-2-8-quincy-released/index.md
> +  due to being prone to false negative results.  It's safer replacement is
s/It's/Its/

2024-11-12 22:29 UTC, zdover23 commented on src/en/news/blog/2024/v17-2-8-quincy-released/index.md
> +  fast-diff mode (`whole_object == true` with `fast-diff` image feature enabled
s/with `fast-diff`/with the `fast-diff`/

2024-11-12 22:29 UTC, zdover23 commented on src/en/news/blog/2024/v17-2-8-quincy-released/index.md
> +- RBD: The option ``--image-id`` has been added to `rbd children` CLI command,
s/to `rbd-children`/to the `rbd-children`/

2024-11-12 22:29 UTC, zdover23 commented on src/en/news/blog/2024/v17-2-8-quincy-released/index.md
> +- RADOS: `get_pool_is_selfmanaged_snaps_mode` C++ API has been deprecated
s/`get_pool_is_selfmanaged_snaps_mode` C++ API/The `get_pool_is_selfmanaged_snaps_mode` C++ API/

2024-11-12 22:29 UTC, zdover23 commented on src/en/news/blog/2024/v17-2-8-quincy-released/index.md
> +  and valid), diff-iterate is now guaranteed to execute locally if exclusive
s/if exclusive/if an exclusive/

2024-11-12 22:29 UTC, zdover23 commented on src/en/news/blog/2024/v17-2-8-quincy-released/index.md
> +- RBD: `RBD_IMAGE_OPTION_CLONE_FORMAT` option has been exposed in Python
s/`RBD_IMAGE_OPTION_CLONE_FORMAT` option/The `RBD_IMAGE_OPTION_CLONE_FORMAT` option/

2024-11-12 22:29 UTC, zdover23 commented on src/en/news/blog/2024/v17-2-8-quincy-released/index.md
> +  bindings via `clone_format` optional parameter to `clone`, `deep_copy` and
s/via `clone_format`/via the `clone_format`/

s/to `clone`/to the `clone`/

2024-11-12 22:29 UTC, zdover23 commented on src/en/news/blog/2024/v17-2-8-quincy-released/index.md
> +- RBD: `RBD_IMAGE_OPTION_FLATTEN` option has been exposed in Python bindings via
s/`RBD_IMAGE_OPTION _FLATTEN` option/The`RBD_IMAGE_OPTION_FLATTEN` option/

2024-11-12 22:29 UTC, zdover23 commented on src/en/news/blog/2024/v17-2-8-quincy-released/index.md
> +  `flatten` optional parameter to `deep_copy` and `migration_prepare` methods.
s/`flatten`/the `flatten/

s/to `deep_copy`/to the `deep_copy`/

2024-11-13 00:20 UTC, yuriw commented
@zdover23 sure

2024-11-13 14:14 UTC, zdover23 approved these changes

2024-11-14 15:46 UTC, yuriw commented
https://wip-yuriw-release-17.2.8-post-main.ceph.io/en/news/blog/2024/v17-2-8-quincy-released/

2024-11-15 16:40 UTC, ljflores approved these changes

2024-11-26 02:13 UTC, merged